In [1]:
import numpy as np

In [5]:
neway= np.array ([
    [1,2,3,],
    [4,5,6],
    [7,8,9]]

)
 

In [6]:
neway

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
 neway[2,1]

8

In [8]:
neway[2]

array([7, 8, 9])

In [9]:
neway[:,2]


array([3, 6, 9])

In [17]:
ay2= np.array ([
    [0,1,2,3,4,5],
    [6,7,8,9,10,11],
    [12,13,14,15,16,17],
    [18,19,20,21,22,23],
    [24,25,26,27,28,29],
    [30,31,32,33,34,35]]

)

ay2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [24]:
np.arange(36).reshape(6, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [18]:
ay2[[2,3],[2,3]]

array([14, 21])

In [19]:
ay2[2:4,2:4]

array([[14, 15],
       [20, 21]])

In [20]:
ay2[::7]

array([[0, 1, 2, 3, 4, 5]])

In [21]:
ay2[0:6,::-7]

array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [22]:
ay2[:,::7]

array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]])

In [23]:
ay2.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [28]:
a3 = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])

a3.shape

(3, 3, 3)

In [31]:
ay2.shape

(6, 6)


# Distribution

In [1]:
import pandas as pd
import numpy as np

In [2]:
np.random.binomial(1, 0.5)

0

In [3]:
np.random.binomial(1000, 0.5)

492

In [9]:
# A real world example. A company drills 9 wild-cat oil exploration wells, each with an estimated probability of success of 0.1. All nine wells fail. What is the probability of that happening?

# Let’s do 20,000 trials of the model, and count the number that generate zero positive results.

sum(np.random.binomial(9, 0.1, 20000) == 0)/20000.
# answer = 0.38885, or 38%.

0.3877